In [24]:
import numpy as np

In [2]:
my_array=np.ndarray([2,4,5,7,8,9,0,4,3])
my_array

array([], shape=(2, 4, 5, 7, 8, 9, 0, 4, 3), dtype=float64)

In [3]:
my_array1=np.arange(1,10)
my_array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
list_1=[1,2,3,4,5]
list_1=np.array(list_1,dtype=np.float64)
list_1

array([1., 2., 3., 4., 5.])

In [5]:
my_multi_array=np.array([[1,2,3],["a","b","c"],[True,False,True]])
my_multi_array[1][1]

np.str_('b')

In [6]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [7]:
np.zeros?

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.ones((5,5)).size
#len(np.ones((5,5)))

25

In [15]:
myarray=np.arange(1,100)
myarray

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
myarray.size

99

In [20]:
myarray.dtype

dtype('int64')

In [31]:
np.random.randint(1,10)

3

In [32]:
np.random.randint(1,1000,size=50)

array([912, 159, 633, 976, 961, 181, 662, 526, 632, 204, 327,  81, 657,
       126, 102, 281, 716, 326, 755, 942, 899, 418, 191, 579, 439, 806,
       255,  63, 562,   1, 287, 275, 469, 899, 424, 837, 948, 216, 590,
       930, 978, 505, 770, 162, 221, 761, 823, 926, 874, 771], dtype=int32)

In [39]:
np.random.choice(['h','t'],size=10)

array(['h', 't', 't', 'h', 't', 't', 'h', 't', 't', 'h'], dtype='<U1')

In [41]:
np.ones((5,10)).shape

(5, 10)

In [42]:
print("Rowa:",np.ones((5,10)).shape[0])
print("Column:",np.ones((5,10)).shape[1])

Rowa: 5
Column: 10


In [8]:
list=[[1,4,5],[6,10,9],[26,6,8]]
myaray1=np.array(list)
myaray1

array([[ 1,  4,  5],
       [ 6, 10,  9],
       [26,  6,  8]])

In [9]:
myaray1.shape

(3, 3)

In [10]:
myaray1[1][1]

np.int64(10)

In [12]:
myaray1[1,1]

np.int64(10)

In [13]:
myaray1[0:2]       #Slicing

array([[ 1,  4,  5],
       [ 6, 10,  9]])

In [14]:
myaray1[0:2,1:3]

array([[ 4,  5],
       [10,  9]])

In [15]:
myaray1[:2,1:]

array([[ 4,  5],
       [10,  9]])

In [18]:
myaray1[1,1]=11    #change number for index
myaray1

array([[ 1,  4,  5],
       [ 6, 11,  9],
       [26,  6,  8]])

In [19]:
myaray1.item(1,1)

11

In [20]:
#get specific index

In [35]:
myarr1=np.array([1,4,6,7,8,3,6,9])
np.take(myarr1,[0,3,5])

array([1, 7, 3])

In [36]:
#np.put(myarr1,[0,3,5],[0,0,0])
myarr1

array([1, 4, 6, 7, 8, 3, 6, 9])

In [38]:
myarr1[-2]

np.int64(6)

In [39]:
myarr1[0:-2]

array([1, 4, 6, 7, 8, 3])

In [40]:
myarr1[1:-1]        #Reverse

array([4, 6, 7, 8, 3, 6])

In [44]:
myarr1[myarr1%2== 0 ]      #Conditional

array([4, 6, 8, 6])

In [46]:
myarr1[(myarr1%2==0) & (myarr1>5)]      

array([6, 8, 6])

In [65]:
gender_data=np.random.choice(("M","F"),size=500)
gender_data

array(['F', 'M', 'M', 'F', 'F', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'M',
       'M', 'M', 'M', 'F', 'M', 'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F',
       'F', 'F', 'F', 'F', 'M', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'F',
       'F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F', 'F', 'M', 'F',
       'F', 'M', 'F', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'M',
       'F', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'M', 'F', 'M',
       'F', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'M', 'M',
       'M', 'M', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'F', 'M', 'M',
       'M', 'M', 'F', 'F', 'M', 'F', 'M', 'F', 'F', 'M', 'F', 'F', 'M',
       'F', 'M', 'F', 'F', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'F', 'M',
       'F', 'M', 'F', 'M', 'F', 'M', 'F', 'F', 'F', 'M', 'M', 'M', 'F',
       'M', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'M', 'M', 'F', 'F',
       'M', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'F', 'F', 'M',
       'F', 'F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'F', 'M

In [60]:
np.unique(gender_data)  #Unique slice

array(['F', 'M'], dtype='<U1')

#Reshapping Array____

In [61]:
gender_data.reshape?

Docstring:
a.reshape(shape, /, *, order='C', copy=None)

Returns an array containing the same data with a new shape.

Refer to `numpy.reshape` for full documentation.

See Also
--------
numpy.reshape : equivalent function

Notes
-----
Unlike the free function `numpy.reshape`, this method on `ndarray` allows
the elements of the shape parameter to be passed in as separate arguments.
For example, ``a.reshape(10, 11)`` is equivalent to
``a.reshape((10, 11))``.
Type:      builtin_function_or_method

In [62]:
#gender_data.reshape((50,10))

In [63]:
#gender_data.reshape((10,10,5))

In [64]:
gender_data.resize((10,10))
gender_data

array([['M', 'F', 'M', 'F', 'M', 'M', 'F', 'M', 'M', 'M'],
       ['M', 'F', 'F', 'F', 'F', 'F', 'M', 'F', 'M', 'F'],
       ['M', 'M', 'M', 'M', 'M', 'F', 'F', 'M', 'M', 'F'],
       ['M', 'F', 'F', 'M', 'F', 'M', 'M', 'M', 'M', 'F'],
       ['M', 'M', 'M', 'F', 'F', 'M', 'F', 'F', 'F', 'F'],
       ['M', 'F', 'F', 'F', 'F', 'F', 'M', 'M', 'M', 'M'],
       ['F', 'M', 'M', 'M', 'M', 'F', 'M', 'M', 'M', 'F'],
       ['F', 'F', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M'],
       ['M', 'M', 'F', 'F', 'M', 'M', 'M', 'F', 'F', 'M'],
       ['M', 'M', 'F', 'M', 'M', 'M', 'M', 'F', 'F', 'F']], dtype='<U1')

In [68]:
myarr3=np.random.randint(1,10,size=(3,3))
myarr3

array([[8, 8, 4],
       [2, 4, 2],
       [4, 1, 5]], dtype=int32)

In [73]:
myarr3.transpose()

array([[8, 2, 4],
       [8, 4, 1],
       [4, 2, 5]], dtype=int32)

In [76]:
#myarr3.transpose?

In [78]:
myarr3.transpose((0,1))

array([[8, 8, 4],
       [2, 4, 2],
       [4, 1, 5]], dtype=int32)

In [80]:
myarr3.swapaxes(0,1)

array([[8, 2, 4],
       [8, 4, 1],
       [4, 2, 5]], dtype=int32)

In [81]:
myarr3.swapaxes(1,0)

array([[8, 2, 4],
       [8, 4, 1],
       [4, 2, 5]], dtype=int32)

In [85]:
myarr3.flatten()

array([8, 8, 4, 2, 4, 2, 4, 1, 5], dtype=int32)

In [87]:
myarr3.flatten(order="f")    #by row

array([8, 2, 4, 8, 4, 1, 4, 2, 5], dtype=int32)

In [89]:
myarr3.sort()
myarr3

array([[4, 8, 8],
       [2, 2, 4],
       [1, 4, 5]], dtype=int32)

In [90]:
myarr3.sort(axis=0)
myarr3                    #0 by row

array([[1, 2, 4],
       [2, 4, 5],
       [4, 8, 8]], dtype=int32)

In [91]:
myarr3.sort(axis=1)      #1 by column      
myarr3

array([[1, 2, 4],
       [2, 4, 5],
       [4, 8, 8]], dtype=int32)

In [97]:
my_new_arr_1=np.arange(1,10).reshape((3,3))
my_new_arr_2=np.arange(11,20).reshape((3,3))
print(my_new_arr_1)
print("------")
print(my_new_arr_2)
np.vstack((my_new_arr_1,my_new_arr_2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------
[[11 12 13]
 [14 15 16]
 [17 18 19]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [98]:
np.hstack((my_new_arr_1,my_new_arr_2))

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

In [111]:
ss_arr_5=np.random.randint(10,size=(2,20))
print(ss_arr_5)
np.hsplit(ss_arr_5,(7,15))

[[9 9 7 5 4 5 5 1 5 1 9 4 1 1 0 6 1 2 0 3]
 [3 5 4 8 9 2 0 0 5 3 7 3 8 1 6 0 2 8 3 3]]


[array([[9, 9, 7, 5, 4, 5, 5],
        [3, 5, 4, 8, 9, 2, 0]], dtype=int32),
 array([[1, 5, 1, 9, 4, 1, 1, 0],
        [0, 5, 3, 7, 3, 8, 1, 6]], dtype=int32),
 array([[6, 1, 2, 0, 3],
        [0, 2, 8, 3, 3]], dtype=int32)]

In [117]:
ss_arr_6=np.random.randint(10,size=(10,2))
print(ss_arr_6)
np.vsplit(ss_arr_6,(2,5))

[[2 4]
 [4 2]
 [4 2]
 [0 3]
 [7 5]
 [0 7]
 [0 0]
 [6 5]
 [6 7]
 [7 9]]


[array([[2, 4],
        [4, 2]], dtype=int32),
 array([[4, 2],
        [0, 3],
        [7, 5]], dtype=int32),
 array([[0, 7],
        [0, 0],
        [6, 5],
        [6, 7],
        [7, 9]], dtype=int32)]

Copy

In [21]:
my_arr1=np.random.randint(100,size=(3,3))
my_arr1

array([[64, 24, 21],
       [ 8, 83, 10],
       [ 2, 32, 86]], dtype=int32)

In [22]:
copy_my_arr1=my_arr1
#copy_my_arr1.sort()
#print(copy_my_arr1)
print(my_arr1)

[[64 24 21]
 [ 8 83 10]
 [ 2 32 86]]


In [23]:
#view_my_arr1=my_arr1.view()
#view_my_arr1.sort()
#print(view_my_arr1)
print(my_arr1)

[[64 24 21]
 [ 8 83 10]
 [ 2 32 86]]


In [24]:
copy_my_arr1=my_arr1.copy()
copy_my_arr1.sort()
print(copy_my_arr1)
print(my_arr1)

[[21 24 64]
 [ 8 10 83]
 [ 2 32 86]]
[[64 24 21]
 [ 8 83 10]
 [ 2 32 86]]


<h>Basic Math<h>

In [35]:
list1=np.array([1,5,3,7,8,0,3])
list2=np.array([3,7,2,6,9,6,8])
list3=list1 + list2                      
list3

array([ 4, 12,  5, 13, 17,  6, 11])

In [36]:
#list1.sum()        #sum=sum all list
#print(list2.sum())
#print(list2.cumsum())

In [41]:
print(list1.min())
print(list1.max())

0
8


In [42]:
print(list1.argmax())

4


In [44]:
np.add(list1,list2)       #remainder=%

array([ 4, 12,  5, 13, 17,  6, 11])

In [46]:
print(list2)
np.power(list2,2)

[3 7 2 6 9 6 8]


array([ 9, 49,  4, 36, 81, 36, 64])

In [49]:
my_arr2_square=np.power(list2,2)          #astype=changing type
print(np.sqrt(my_arr2_square).astype(int))

[3 7 2 6 9 6 8]


In [51]:
#absolute= - into +
np.absolute(np.arange(-10,-1))

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [53]:
np.gcd.reduce([9,12,15])

np.int64(3)

In [55]:
np.lcm.reduce([9,12,15])

np.int64(180)

In [58]:
np.floor([1.2,2.7]) #round down

array([1., 2.])

In [59]:
np.ceil([1.2,2.5])  #round up

array([2., 3.])

In [60]:
list2**2  #power or

array([ 9, 49,  4, 36, 81, 36, 64])

In [70]:
print(list2)
list2.argmax(axis=0)

[3 7 2 6 9 6 8]


np.int64(4)

In [113]:
studentdata=[["Maths","Science","English","Urdu","Shindi"],
             [50,60,70,80,40],
             [30,70,80,40,60],
             [20,40,60,80,90],
             [30,60,80,50,40],
             [40,40,30,60,80]]
subjects=studentdata.pop(0)
studentdata=np.array(studentdata)
max_subject=studentdata.argmax(axis=0)
max_student=studentdata.argmax(axis=1)
#print(max_student,max_subject)
for i in range(0,len(subjects)):
    print(f"{subjects[i]}:max marks:{studentdata[max_subject[i],i]}")
for loc,student in enumerate(studentdata):
    print(f"student no:{loc+1}\nMax marks:{student[max_student[loc]]} in subject:{subjects[max_student[loc]]}")
    print("_________")
    
    

Maths:max marks:50
Science:max marks:70
English:max marks:80
Urdu:max marks:80
Shindi:max marks:90
student no:1
Max marks:80 in subject:Urdu
_________
student no:2
Max marks:80 in subject:English
_________
student no:3
Max marks:90 in subject:Shindi
_________
student no:4
Max marks:80 in subject:English
_________
student no:5
Max marks:80 in subject:Shindi
_________


In [5]:
student_data={"std-1":{"Maths":85,"Urdu":70,"Sindhi":40,"Chemistry":90,"Physics":60},
              "std-2":{"Maths":70,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60},
              "std-3":{"Maths":80,"Urdu":70,"Sindhi":95,"Chemistry":90,"Physics":60},
              "std-4":{"Maths":80,"Urdu":70,"Sindhi":50,"Chemistry":85,"Physics":60},
              "std-5":{"Maths":80,"Urdu":75,"Sindhi":40,"Chemistry":90,"Physics":60}}
students=list(student_data.keys())
subjects=list(next(iter(student_data.values())).keys())
marks=np.array([list(s.values())for s in student_data.values()])
print(marks)
max_subject=marks.argmax(axis=0)
min_subject=marks.argmin(axis=0)
max_student=marks.argmax(axis=1)
min_student=marks.argmin(axis=1)
print(max_student)
for i in range(0,len(subjects)):
    print(f"{subjects[i]}:max marks:{marks[max_subject[i],i]}")
for loc,student in enumerate(marks):
    print(f"student no:{loc+1}\nMax marks:{student[max_student[loc]]} in subject:{subjects[max_student[loc]]}")
    print("_________")
sum_row=np.sum(marks,axis=0)
print(sum_row)
sums=sum_row.argmax()
total=sum_row.max()
print(f"Total Highest Marks score:{total}={marks[sums]} in student 4")

[[85 70 40 90 60]
 [70 75 40 90 60]
 [80 70 95 90 60]
 [80 70 50 85 60]
 [80 75 40 90 60]]
[3 3 2 3 3]
Maths:max marks:85
Urdu:max marks:75
Sindhi:max marks:95
Chemistry:max marks:90
Physics:max marks:60
student no:1
Max marks:90 in subject:Chemistry
_________
student no:2
Max marks:90 in subject:Chemistry
_________
student no:3
Max marks:95 in subject:Sindhi
_________
student no:4
Max marks:85 in subject:Chemistry
_________
student no:5
Max marks:90 in subject:Chemistry
_________
[395 360 265 445 300]
Total Highest Marks score:445=[80 70 50 85 60] in student 4


In [3]:
temps=np.array([[30,32,31,29,28,27,26],
               [22,21,23,24,25,26,24],
               [15,17,16,18,19,20,21]])
max_city=temps.max()
print(f"Max temperature in City A:{max_city}C")
max_day=temps.sum(axis=0)
day=max_day.argmax()
print(f"Day with high temperature in Day {day}")
city=temps.sum(axis=1)
at_city=city.max()
print(f"Generally Warmer is City A:Total temp:{at_city}C")

Max temperature in City A:32C
Day with high temperature in Day 5
Generally Warmer is City A:Total temp:203C


In [4]:
#NEW WORK
#1.Dot Product
#2. Determinant
#3.Inverse
#4.Inner Matrix
#5.Power

In [5]:
my_arr1=np.array([[1,2],[3,4]])              #Dot product   row by column
my_arr2=np.array([[2,4],[6,9]])
np.linalg.multi_dot([my_arr1,my_arr2])

array([[14, 22],
       [30, 48]])

In [8]:
np.linalg.det(my_arr1)                      #Determinant

np.float64(-2.0000000000000004)

In [9]:
np.linalg.inv(my_arr2)                      #Inverse

array([[-1.5       ,  0.66666667],
       [ 1.        , -0.33333333]])

In [10]:
np.inner(my_arr1,my_arr2)                 #Inner   row by row                 

array([[10, 24],
       [22, 54]])

In [11]:
np.pow(my_arr1,2)                       #Power

array([[ 1,  4],
       [ 9, 16]])

In [13]:
#Work
#Arthmetic Mean
#Geometrical Mean

In [53]:
profit=np.array([-0.10,0.20,0.80,-0.30,-0.40,-0.20,0.30,0.60,-0.10,0.20])

In [54]:
np.pow(profit.prod(),1/len(profit))

C:\Users\H S COMPUTER S HYD\AppData\Local\Temp\ipykernel_4784\1463819382.py:1: RuntimeWarning: invalid value encountered in power
  np.pow(profit.prod(),1/len(profit))


np.float64(nan)

In [49]:
#(2500+(2500*))

In [9]:
factor=profit + 1
pof=factor.prod()
amount=9000*pof
print(amount)
print(f'A Mean:{profit.mean():2f}')
geom=np.pow(factor.prod(),1/len(factor))-1
print(f"G Mean:{geom}")

NameError: name 'profit' is not defined

In [58]:
9000+(9000*0.04)*10

12600.0

In [5]:
#NEW WORK
#np.where all empty values index in data set

In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data=genfromtxt(r"E:\python\p1(class).csv",delimiter=",",dtype="str")

In [4]:
data

array([['Year', 'Profit Percentage', 'Additional Investment',
        'Total Amount'],
       ['1', '25%', '0', '6250'],
       ['2', '-30%', '0', '4375'],
       ['3', '22%', '0', '5337.5'],
       ['4', '28%', '0', '6832'],
       ['5', '25%', '2000', '10840'],
       ['6', '5%', '0', '11382'],
       ['7', '-25%', '0', '8536.5'],
       ['8', '30%', '0', '11097.45'],
       ['9', '-22%', '0', '8656.01'],
       ['10', '28%', '0', '11079.69']], dtype='<U21')

In [8]:
data=np.delete(data,0,axis=0)

In [9]:
data

array([['1', '25%', '0', '6250'],
       ['2', '-30%', '0', '4375'],
       ['3', '22%', '0', '5337.5'],
       ['4', '28%', '0', '6832'],
       ['5', '25%', '2000', '10840'],
       ['6', '5%', '0', '11382'],
       ['7', '-25%', '0', '8536.5'],
       ['8', '30%', '0', '11097.45'],
       ['9', '-22%', '0', '8656.01'],
       ['10', '28%', '0', '11079.69']], dtype='<U21')

In [45]:
percentage=data[:,1]
integer=np.array([int(val.strip("%"))for val in percentage])
print(integer)

[ 25 -30  22  28  25   5 -25  30 -22  28]


In [50]:
profit=integer/100
profit

array([ 0.25, -0.3 ,  0.22,  0.28,  0.25,  0.05, -0.25,  0.3 , -0.22,
        0.28])

In [48]:
initial=9000
factor=profit+1
gmean=np.pow(factor.prod(),1/len(factor))-1
gmean

np.float64(0.05730098145198537)

In [51]:
data=genfromtxt(r"E:\python\p1(class).csv",delimiter=",",dtype="str")

In [53]:
columns=data[0]
data=np.delete(data,0,axis=0)

In [54]:
data

array([['1', '25%', '0', '6250'],
       ['2', '-30%', '0', '4375'],
       ['3', '22%', '0', '5337.5'],
       ['4', '28%', '0', '6832'],
       ['5', '25%', '2000', '10840'],
       ['6', '5%', '0', '11382'],
       ['7', '-25%', '0', '8536.5'],
       ['8', '30%', '0', '11097.45'],
       ['9', '-22%', '0', '8656.01'],
       ['10', '28%', '0', '11079.69']], dtype='<U21')

In [79]:
profit=np.array([pro.replace("%",'')for pro in data[:,1]]).astype("float")
initial=5000
additional=data[:,2].astype("float")
profits=profit/100
factor=(profits)+1
print(f"A Mean:{np.mean(profit)}")
print(f"G Mean:{np.pow(factor.prod(),1/len(factor))-1}")
total_amount=initial
for a,p in zip(additional,profits):
    total_amount+=a
    total_amount*=p+1
total_amount

A Mean:8.6
G Mean:0.05730098145198537


np.float64(11284.11648)